apk-update(8)

# NAME

apk update - update repository indexes

# SYNOPSIS

*apk update*

# DESCRIPTION

*apk update* fetches the index from all configured package repositories. See
*apk-repositories*(5) for more information on configuring package repositories.

# OPTIONS

*apk update* does not support any specific options. See *apk*(8) for global
options.

# AUTHORS

Natanael Copa <ncopa@alpinelinux.org>++
Timo Teräs <_timo.teras@iki.fi_>
