#!/usr/bin/lua5.3
-- Generate Zsh completion for apk(8) from scdoc manpages

local template_main = [==[
#compdef apk

# apk(8) completion                                         *- shell-script -*-
# Automatically generated by apk-tools (src/genhelp_zsh.lua). Do not modify.

__apk_installed_pkgs() {
	local -a pkgs
	pkgs=(${(f)"$(apk query --summarize name --installed "${PREFIX}*" 2>/dev/null)"})
	compadd -a pkgs
}

__apk_available_pkgs() {
	local -a pkgs
	pkgs=(${(f)"$(apk query --summarize name --available "${PREFIX}*" 2>/dev/null)"})
	compadd -a pkgs
}

_apk() {
	local curcontext="$curcontext" state line
	typeset -A opt_args

	_arguments -C \
%s		'1: :->applet' \
		'*::arg:->args'

	case $state in
		applet)
			local -a applets
			applets=(
%s			)
			_describe -t applets 'apk command' applets
			;;
		args)
			case $line[1] in
%s			esac
			;;
	esac
}

_apk "$@"
]==]

local M = {}

-- Take the first sentence of a (possibly multi-line) description, same
-- cutoff rule genhelp_bash.lua uses: stop at ". " or a trailing ".".
local function first_sentence(text)
	local i = text:find("%.%s")
	if not i then i = text:find("%.$") end
	if i then text = text:sub(1, i - 1) end
	return text
end

-- Escape text for use inside a single-quoted zsh _arguments spec, where
-- '[', ']' and ':' are field delimiters and must be escaped to appear
-- literally, and embedded single quotes must close/re-open the string.
local function zsh_escape(s)
	s = s:gsub("\\", "\\\\")
	s = s:gsub("%[", "\\[")
	s = s:gsub("%]", "\\]")
	s = s:gsub(":", "\\:")
	s = s:gsub("'", "'\\''")
	return s
end

-- Escape text for a 'name:description' entry consumed by _describe.
local function describe_escape(s)
	s = s:gsub("\\", "\\\\")
	s = s:gsub(":", "\\:")
	s = s:gsub("'", "'\\''")
	return s
end

-- Applets needing package name completion (mirrors genhelp_bash.lua)
local applet_wildcard = {
	add="__apk_available_pkgs",
	del="__apk_installed_pkgs",
	dot="__apk_available_pkgs",
	fetch="__apk_available_pkgs",
	fix="__apk_installed_pkgs",
	index="__apk_available_pkgs",
	info="__apk_available_pkgs",
	list="__apk_available_pkgs",
	manifest="__apk_available_pkgs",
	mkndx="__apk_available_pkgs",
	policy="__apk_available_pkgs",
	query="__apk_available_pkgs",
	search="__apk_available_pkgs",
	upgrade="__apk_installed_pkgs",
}

-- Build one or more zsh _arguments spec strings (each already wrapped in
-- single quotes) for a single option entry { raw_flags, {desc_lines} }.
local function build_opt_specs(opt)
	local desc = zsh_escape(first_sentence(table.concat(opt[2], " ")))
	local plain, specs = {}, {}

	for flag in opt[1]:gmatch("(%-%-?[^ ,]+)") do
		local base, val = flag:match("(.*)%[=(%w+)%]")
		if val == "BOOL" then
			table.insert(specs, ("'%s[%s]'"):format(base, desc))
			local no_opt = base:gsub("^%-%-", "--no-")
			table.insert(specs, ("'%s[%s]'"):format(no_opt, desc))
		elseif val then
			-- optional value, e.g. --sync[=AUTO]
			table.insert(specs, ("'%s=-[%s]:%s:'"):format(base, desc, val:lower()))
		else
			table.insert(plain, flag)
		end
	end

	-- Group plain boolean aliases (-h, --help) into one mutually-exclusive spec
	if #plain == 1 then
		table.insert(specs, ("'%s[%s]'"):format(plain[1], desc))
	elseif #plain > 1 then
		table.insert(specs, ("'(%s)'{%s}'[%s]'"):format(
			table.concat(plain, " "), table.concat(plain, ","), desc))
	end

	return specs
end

local function collect_arg_specs(doc)
	local specs = {}
	for _, group in ipairs(doc.optgroup or {}) do
		for _, opt in ipairs(group) do
			for _, s in ipairs(build_opt_specs(opt)) do
				table.insert(specs, s)
			end
		end
	end
	return specs
end

function M:generate(app, docs)
	local applets, options, goptions = {}, {}, {}
	local descriptions, main_doc = {}, nil

	for _, doc in ipairs(docs) do
		-- only process section 8
		if doc.mansection == "8" then
			if doc.applet == "APK" then
				goptions = collect_arg_specs(doc)
				main_doc = doc
			else
				table.insert(applets, doc.applet)
				options[doc.applet] = collect_arg_specs(doc)
			end
		end
	end
	table.sort(applets)

	if main_doc then
		for _, cmd in ipairs(main_doc.commands) do
			if type(cmd) == "table" then
				descriptions[cmd[1]] = cmd[2]
			end
		end
	end

	local global_block = {}
	for _, s in ipairs(goptions) do
		table.insert(global_block, "\t\t" .. s .. " \\\n")
	end

	local applets_block = {}
	for _, name in ipairs(applets) do
		local d = describe_escape(descriptions[name] or "")
		table.insert(applets_block, ("\t\t\t\t'%s:%s'\n"):format(name, d))
	end

	local cases_block = {}
	for _, name in ipairs(applets) do
		local opt_lines = {}
		for _, s in ipairs(options[name]) do
			table.insert(opt_lines, "\t\t\t\t\t\t" .. s .. " \\\n")
		end
		local wildcard = applet_wildcard[name]
		local tail = wildcard
			and ("\t\t\t\t\t\t'*:package:%s'\n"):format(wildcard)
			or "\t\t\t\t\t\t'*:arg:_default'\n"
		table.insert(cases_block, ("\t\t\t\t%s)\n\t\t\t\t\t_arguments \\\n%s%s\t\t\t\t\t;;\n"):format(
			name, table.concat(opt_lines), tail))
	end

	return string.format(template_main,
		table.concat(global_block),
		table.concat(applets_block),
		table.concat(cases_block))
end

return M
